dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='latest' PYTHON_VERSION='3.8'
  - NAME='python3.8' PYTHON_VERSION='3.8'
  - NAME='python3.7' PYTHON_VERSION='3.7'
  - NAME='python3.6' PYTHON_VERSION='3.6'
  - NAME='python3.8-alpine3.10' PYTHON_VERSION='3.8'
  - NAME='python3.7-alpine3.8' PYTHON_VERSION='3.7'
  - NAME='python3.6-alpine3.8' PYTHON_VERSION='3.6'

script:
  - bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
