name: Issue Manager

on:
  schedule:
    - cron: "15 17 * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - labeled
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@48bacd85fb842cc27efee25e834edb00aad8f263 # 0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
